#!/bin/bash
cachedir=${XDG_CACHE_HOME:-"$HOME/.cache"}
if [ -d "$cachedir" ]; then
	cache=$cachedir/dmenu_run
else
	cache=$HOME/.dmenu_cache # if no xdg dir, fall back to dotfile in ~
fi

cat $HOME/.cache/dmenu_used | grep -v '^\-*$' | sort | uniq -c | sort -nr | sed 's/.* //' | head -n 5

echo '-------------'

IFS=:
if stest -dqr -n "$cache" ${PATH//:/ }; then
	stest -flx ${PATH//:/ } | sort -u | tee "$cache" | grep -v $( cat $HOME/.cache/dmenu_used | grep -v '^\-*$' | sort| uniq -c | sort -nr | sed 's/.* //' | head -n 5 )
else
	cat "$cache" | grep -v $( cat $HOME/.cache/dmenu_used | grep -v '^\-*$' | sort | uniq -c | sort -nr | sed 's/.* //' | head -n 5 )
fi
